# Generated by Django 5.1.4 on 2025-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='April',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='December',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='February',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='March',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='November',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='October',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='September',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('Monthly_shears', models.IntegerField(null=True)),
                ('Installment', models.IntegerField(null=True)),
                ('Outstanding_Loan', models.IntegerField(null=True)),
                ('Last_month_shears', models.IntegerField(null=True)),
            ],
        ),
    ]
