# Generated by Django 5.1.4 on 2025-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='april',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='august',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='december',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='february',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='january',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='july',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='june',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='may',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='november',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='october',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='september',
            name='Loan_distrinute',
            field=models.IntegerField(null=True),
        ),
    ]
